name: CI com Node.js e Vite

on:
  push:
    branches:
      - master # Altere para 'main' se esse for o seu branch principal
  pull_request:
    branches:
      - master # Altere para 'main' se esse for o seu branch principal
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest # O executor (máquina virtual) onde o job será executado

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        # Este passo é ESSENCIAL e deve ser o primeiro para baixar seu código.

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão LTS recomendada do Node.js para Vite 4.x
          cache: 'npm' # Habilita o cache de dependências do npm para instalações mais rápidas

      - name: Verificar versão do npm e npx (Depuração)
        # Este passo é para depuração. Ele mostrará as versões do npm/npx
        # e onde eles estão no PATH, além de mostrar o PATH completo.
        # Pode ser removido após a correção do problema.
        run: |
          npm -v
          npx -v
          which npm
          which npx
          echo $PATH

      - name: Limpar cache do npm e instalar dependências
        # O 'working-directory' aqui garante que o npm opere na pasta 'src'.
        working-directory: ./src
        run: |
          npm cache clean --force # Limpa o cache do npm (útil se o cache estiver corrompido)
          npm install --force     # Reinstala todas as dependências com força
          # ALTERNATIVA para CI (se você tem package-lock.json, que é recomendado):
          # npm ci

      - name: Verificar se Vite foi instalado no .bin (Depuração)
        # Este passo é para depuração. Ele verificará se o executável 'vite' está presente
        # e quais são suas permissões dentro da pasta 'src/node_modules/.bin/'.
        # Pode ser removido após a correção do problema.
        working-directory: ./src
        run: |
          echo "Verificando permissões e existência de node_modules/.bin/vite:"
          ls -la node_modules/.bin/vite || echo "Vite não encontrado em node_modules/.bin/"
          echo "Conteúdo de node_modules/.bin/:"
          ls -la node_modules/.bin/

      - name: Executar o Projeto (npm run start)
        # Este passo executa o script 'start' definido no seu package.json dentro da pasta 'src'.
        working-directory: ./src
        run: npm run start